# Site settings
title: Shreyas N. Samaga
email: ssamaga@purdue.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD student in the Department of Computer Science at Purdue University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://samagashreyas.github.io" # the base hostname & protocol for your site
twitter_username: samagashreyas
github_username:  samagashreyas
# orcid_id: 
google_scholar_id: _jGCYKMAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "PhD Student"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://plus.google.com/u/0/110288225974212014913"
google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
